### PR TITLE
feat: upgrade fork to 2.11.0

### PR DESCRIPTION
**Pull request by ezenwankwogabriel**
## Description

Update branch to latest upstream @2.11.0

### CODE REVIEW

**Comment by 633kh4ck** [comment]
@ezenwankwogabriel, do you plan to address [build issues](https://github.com/ExodusMovement/walletconnect-monorepo/actions/runs/7541385169/job/20527993092?pr=15)?

**Comment by timlanahan** [comment]
looks like CI checks still failing

**Review by 633kh4ck — APPROVED** [review]
utACK (though most of the test suite pass)

**Review by gutenye — COMMENTED** [review]
post-merge utACK

**Pull request merged**
